### ISSUE TITLE
Allowing ?mixed

### ISSUE THREAD

**Issue by ondrejmirtes** [Danack/MixedRFC#12]
Hi, I'm reacting to [your tweet](https://twitter.com/MrDanack/status/1248911422186237953) whn you're asking me to review this RFC.

Overall I like it, I would only change one thing - `?mixed` should be allowed. The RFC doesn't talk about `mixed|null` so I think you want to allow it. There are many situations like this that PHP 8 allows and I don't see why `mixed|null` should be cut from that. The goal is to stay consistent with the rest of the language and to not create obstacles for the user.

For example you can write `Exception|InvalidArgumentException` and PHP is fine with that AFAIK, although the type can be normalized to `Exception` - because `InvalidArgumentException` is already part of that. `mixed|null` is just another example of that.

**Comment by Danack** [comment]
Thanks, that seems reasonable to me.

@kocsismate okay to change?

**Comment by kocsismate** [comment]
@Danack To be honest, I'm not very impressed. I think it would be worth to ask it on the ML before changing the RFC.

While it's true that `Exception|InvalidArgumentException` is allowed, generally, redundant types are disallowed. Some examples: `?int|null`, `bool|false`, `object` with any other class, `iterable|array`, `iterable|Traversable`. In my opinion, disallowing `?mixed` would be more consistent with this behaviour.

Plus, I'd argue that the `Exception|InvalidArgumentException` type is redundant, since you might want to act differently if a parameter/return type is a regular `Exception` or a specific kind of it (which can have additional methods/properties).

**Comment by ondrejmirtes** [comment]
> generally, redundant types are disallowed. Some examples

I didn’t know this. Thanks!

**Comment by kocsismate** [comment]
@ondrejmirtes You're welcome! And thank you for giving feedback about the RFC :)

**Comment by Danack** [comment]
I also did not know that.

I think that's one area that may not have been thought through thoroughly.....and so anyone who wants better consistency in that area can do that in a separate RFC. I updated the words to reflect that.

**Comment by kocsismate** [comment]
@Danack To be honest, `?int|null` is disallowed at the parser level, but the other examples I gave are explicitly dealt with during compilation.

So I agree with not supporting `?mixed` for now, so that it can be added later if people really want it. :)

**Comment by Danack** [comment]
@kocsismate So those words I wrote are not quite accurate? Can you update them to be more accurate please.

**Comment by kocsismate** [comment]
@Danack I'll have a look at it! But only `?int|null` is not quite accurate.

**Comment by Danack** [comment]
I think the words are good enough now, so will close this.
